apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-ms
  template:
    metadata:
      labels:
        app: order-ms
    spec:
      containers:
      - name: order-ms
        image: 975050002971.dkr.ecr.us-east-1.amazonaws.com/order-ms:latest
        ports:
        - containerPort: 3001
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 15
        resources:
          requests:
            cpu: 10m
        imagePullPolicy: Always        

---
apiVersion: v1
kind: Service
metadata:
  name: svc-order-ms
spec:
  type: LoadBalancer
  selector:
    app: order-ms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
